api:
  diary:
    base-url: http://localhost:8080
    endpoints:
      all:
        url: http://localhost:8080/api/diary/all
        method: GET
      byId:
        url: http://localhost:8080/api/diary/{id}
        method: GET
      create:
        url: http://localhost:8080/api/diary
        method: POST
      update:
        url: http://localhost:8080/api/diary/{id}
        method: PUT
      delete:
        url: http://localhost:8080/api/diary/{id}
        method: DELETE